UPDATE `websites` SET `id_website` = 2,`nom` = 'Yungi_design',`adresse_1` = 'Rue Etraz 2',`adresse_2` = NULL,`npa` = 1003,`ville` = 'Lausanne',`tel` = '+41 78 769 00 80',`mobile` = '+41 78 769 00 80',`email` = 'ygyongy@tradiluxe.com' WHERE `websites`.`id_website` = 1;

UPDATE `langues` SET `id_langue` = 1,`code_langue` = 'fr',`nom_langue` = 'français',`position` = 1,`actif` = '1' WHERE `langues`.`id_langue` = 1;
UPDATE `langues` SET `id_langue` = 2,`code_langue` = 'de',`nom_langue` = 'deutsch',`position` = 2,`actif` = '1' WHERE `langues`.`id_langue` = 2;
UPDATE `langues` SET `id_langue` = 3,`code_langue` = 'en',`nom_langue` = 'english',`position` = 3,`actif` = '1' WHERE `langues`.`id_langue` = 3;

UPDATE `types_contenus` SET `id_type_contenu` = 1,`nom_type_contenu` = 'page',`actif` = '1' WHERE `types_contenus`.`id_type_contenu` = 1;
UPDATE `types_contenus` SET `id_type_contenu` = 2,`nom_type_contenu` = 'matrice',`actif` = '1' WHERE `types_contenus`.`id_type_contenu` = 2;
UPDATE `types_contenus` SET `id_type_contenu` = 3,`nom_type_contenu` = 'form',`actif` = '1' WHERE `types_contenus`.`id_type_contenu` = 3;
UPDATE `types_contenus` SET `id_type_contenu` = 4,`nom_type_contenu` = 'block',`actif` = '1' WHERE `types_contenus`.`id_type_contenu` = 4;

UPDATE `groupes` SET `id_groupe` = 1,`nom_groupe` = 'Administrateur',`droit` = 'UPEA' WHERE `groupes`.`id_groupe` = 1;
UPDATE `groupes` SET `id_groupe` = 2,`nom_groupe` = 'Editeur',`droit` = 'UPE' WHERE `groupes`.`id_groupe` = 2;
UPDATE `groupes` SET `id_groupe` = 3,`nom_groupe` = 'Professionnel',`droit` = 'UP' WHERE `groupes`.`id_groupe` = 3;
UPDATE `groupes` SET `id_groupe` = 4,`nom_groupe` = 'User',`droit` = 'U' WHERE `groupes`.`id_groupe` = 4;

UPDATE `utilisateurs` SET `id_utilisateur` = 1,`nom_utilisateur` = 'Gyongy',`prenom_utilisateur` = 'Yann',`login_utilisateur` = 'ygyongy',`pwd_utilisateur` = '0e9059c917c0b475ed2b9469a7d3e597',`inscription_utilisateur` = '2011-07-24 05:07:10',`groupes_id_groupe` = 1,`langues_id_langue` = 1 WHERE `utilisateurs`.`id_utilisateur` = 1;

UPDATE `categories` SET `id_categorie` = 1,`nom_categorie` = 'Accueil',`principal` = '1',`actif` = '1',`position` = 1,`droit_categorie` = '',`langues_id_langue` = 1 WHERE `categories`.`id_categorie` = 1 AND `categories`.`langues_id_langue` = 1;
UPDATE `categories` SET `id_categorie` = 1,`nom_categorie` = 'Hause',`principal` = '1',`actif` = '1',`position` = 1,`droit_categorie` = '',`langues_id_langue` = 2 WHERE `categories`.`id_categorie` = 1 AND `categories`.`langues_id_langue` = 2;
UPDATE `categories` SET `id_categorie` = 1,`nom_categorie` = 'Home',`principal` = '1',`actif` = '1',`position` = 1,`droit_categorie` = '',`langues_id_langue` = 3 WHERE `categories`.`id_categorie` = 1 AND `categories`.`langues_id_langue` = 3;
UPDATE `categories` SET `id_categorie` = 2,`nom_categorie` = 'Entreprise',`principal` = '1',`actif` = '1',`position` = 2,`droit_categorie` = '',`langues_id_langue` = 1 WHERE `categories`.`id_categorie` = 2 AND `categories`.`langues_id_langue` = 1;
UPDATE `categories` SET `id_categorie` = 2,`nom_categorie` = 'Firma',`principal` = '1',`actif` = '1',`position` = 2,`droit_categorie` = '',`langues_id_langue` = 2 WHERE `categories`.`id_categorie` = 2 AND `categories`.`langues_id_langue` = 2;
UPDATE `categories` SET `id_categorie` = 2,`nom_categorie` = 'Entreprise',`principal` = '1',`actif` = '1',`position` = 2,`droit_categorie` = '',`langues_id_langue` = 3 WHERE `categories`.`id_categorie` = 2 AND `categories`.`langues_id_langue` = 3;
UPDATE `categories` SET `id_categorie` = 3,`nom_categorie` = 'Catalogue',`principal` = '1',`actif` = '1',`position` = 3,`droit_categorie` = '',`langues_id_langue` = 1 WHERE `categories`.`id_categorie` = 3 AND `categories`.`langues_id_langue` = 1;
UPDATE `categories` SET `id_categorie` = 3,`nom_categorie` = 'Katalogue',`principal` = '1',`actif` = '1',`position` = 3,`droit_categorie` = '',`langues_id_langue` = 2 WHERE `categories`.`id_categorie` = 3 AND `categories`.`langues_id_langue` = 2;
UPDATE `categories` SET `id_categorie` = 3,`nom_categorie` = 'Collection',`principal` = '1',`actif` = '1',`position` = 3,`droit_categorie` = '',`langues_id_langue` = 3 WHERE `categories`.`id_categorie` = 3 AND `categories`.`langues_id_langue` = 3;
UPDATE `categories` SET `id_categorie` = 4,`nom_categorie` = 'Admin',`principal` = '1',`actif` = '1',`position` = 4,`droit_categorie` = '',`langues_id_langue` = 1 WHERE `categories`.`id_categorie` = 4 AND `categories`.`langues_id_langue` = 1;
UPDATE `categories` SET `id_categorie` = 5,`nom_categorie` = 'block_user',`principal` = '0',`actif` = '1',`position` = 1,`droit_categorie` = '',`langues_id_langue` = 1 WHERE `categories`.`id_categorie` = 5 AND `categories`.`langues_id_langue` = 1;


UPDATE `sous_categories` SET `id_sous_categorie` = 1,`nom_sous_categorie` = 'Sous-accueil',`principal` = '0',`actif` = '1',`position` = 1,`categories_id_categorie` = 1,`langues_id_langue` = 1 WHERE `sous_categories`.`id_sous_categorie` = 1 AND `sous_categories`.`langues_id_langue` = 1;
UPDATE `sous_categories` SET `id_sous_categorie` = 2,`nom_sous_categorie` = 'création d''utilisateur',`principal` = '0',`actif` = '1',`position` = 1,`categories_id_categorie` = 4,`langues_id_langue` = 1 WHERE `sous_categories`.`id_sous_categorie` = 2 AND `sous_categories`.`langues_id_langue` = 1;

UPDATE `contenus` SET `id_contenu` = 1,`titre_html` = 'Bienvenue sur notre page d''accueil',`titre` = 'Accueil',`sous_titre` = 'Accueil',`contenu` = '{"titre":"Accueil","contenu":"page d''accueil"}',`position` = 1,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 1,`types_contenus_id_types_contenus` = 1,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 1 WHERE `contenus`.`id_contenu` = 9 AND `contenus`.`langues_id_langue` = 1;
UPDATE `contenus` SET `id_contenu` = 1,`titre_html` = 'Wilkommen aus unsere Hause Seite',`titre` = 'Hause',`sous_titre` = 'Hause',`contenu` = '{"titre":"Hause", "contenu":"Wilkommen zu unsere neue webiste"}',`position` = 1,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 1,`types_contenus_id_types_contenus` = 1,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 2 WHERE `contenus`.`id_contenu` = 9 AND `contenus`.`langues_id_langue` = 2;
UPDATE `contenus` SET `id_contenu` = 1,`titre_html` = 'Welcome on our new homepage',`titre` = 'home',`sous_titre` = 'home',`contenu` = '{"titre":"Home", "contenu":"Welcome on our website"}',`position` = 1,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 1,`types_contenus_id_types_contenus` = 2,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 3 WHERE `contenus`.`id_contenu` = 9 AND `contenus`.`langues_id_langue` = 3;
UPDATE `contenus` SET `id_contenu` = 2,`titre_html` = 'welcome on our new second homepage',`titre` = 'home 2',`sous_titre` = 'home 2',`contenu` = '{"titre":"Home 2", "contenu":"Funk 4 ever!!!"}',`position` = 2,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 1,`types_contenus_id_types_contenus` = 1,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 3 WHERE `contenus`.`id_contenu` = 11 AND `contenus`.`langues_id_langue` = 3;
UPDATE `contenus` SET `id_contenu` = 3,`titre_html` = 'formulaire d''ajout de contenu',`titre` = 'formulaire',`sous_titre` = 'd''ajout de contenu',`contenu` = '{"titre":"Ajout de contenu",\r\n	"contenu":{"action":"\\/site_perso_yungi\\/fr\\/Admin\\/",\r\n				"enctype":"application\\/x-www-form-urlencoded",\r\n				"method":"POST",\r\n				"id":"ajout_type_page",\r\n				"fields":[{"display_name":"titre html",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"titre_html",\r\n							"name":"titre_html",\r\n							"value":""\r\n						},\r\n						{\r\n							"display_name":"keywords html",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"keywords",\r\n							"name":"keywords",\r\n							"value":""\r\n						},\r\n						{\r\n							"display_name":"titre de la bannière",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"titre_banner",\r\n							"name":"titre_banner",\r\n							"value":""\r\n						},\r\n						{\r\n							"display_name":"sous-titre de la bannière",\r\n							"template":"textarea",\r\n							"class":"richtext_editor",\r\n							"id":"sous_titre_banner",\r\n							"name":"sous_titre_banner",\r\n							"value":""\r\n						},\r\n						{\r\n							"display_name":"Corps du block",\r\n							"template":"textarea",\r\n							"class":"richtext_editor",\r\n							"id":"block_content",\r\n							"name":"block_content",\r\n							"value":""						\r\n						},\r\n						{\r\n							"display_name":"Fichier a proposer",\r\n							"template":"input",\r\n							"type":"file",\r\n							"class":"",\r\n							"id":"file_content",\r\n							"name":"file_content",\r\n							"value":""							\r\n						},\r\n						{\r\n							"type":"submit",\r\n							"template":"input",\r\n							"class":"",\r\n							"id":"submit",\r\n							"name":"submit",\r\n							"value":"envoyer donnees"\r\n						}]\r\n			}\r\n}',`position` = 1,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 4,`types_contenus_id_types_contenus` = 3,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 1 WHERE `contenus`.`id_contenu` = 12 AND `contenus`.`langues_id_langue` = 1;
UPDATE `contenus` SET `id_contenu` = 4,`titre_html` = 'formulaire de connexion',`titre` = 'connexion',`sous_titre` = 'des utilisateurs',`contenu` = '{"titre":"Connexion",\r\n	"id_fieldset":"fieldset_connexion_user",\r\n	"contenu":{"action":"",\r\n			"enctype":"application\\/x-www-form-urlencoded",\r\n			"method":"POST",\r\n			"id":"connexion_user",\r\n			"name_form":"connexion_user",\r\n			"evenement_form":"onsubmit=\\"return requestAuthentificationUser(''/site_perso_yungi/ajax/'',this, printData)\\"",\r\n			"fields":[{"display_name":"login",\r\n						"template":"input",\r\n						"type":"text",\r\n						"class":"",\r\n						"id":"login",\r\n						"name":"login"\r\n					},\r\n					{\r\n						"display_name":"password",\r\n						"template":"input",\r\n						"type":"password",\r\n						"class":"",\r\n						"id":"pwd",\r\n						"name":"pwd"\r\n					},\r\n					{\r\n						"type":"reset",\r\n						"template":"input",\r\n						"class":"fleft",\r\n						"id":"reset_user_form",\r\n						"name":"reset_user_form",\r\n						"value":"effacer"\r\n					},\r\n					{\r\n						"type":"submit",\r\n						"template":"input",\r\n						"class":"fleft",\r\n						"id":"connexion_user",\r\n						"name":"connexion_user",\r\n						"value":"connexion"\r\n					}]}}',`position` = 1,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 5,`types_contenus_id_types_contenus` = 4,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 1 WHERE `contenus`.`id_contenu` = 13 AND `contenus`.`langues_id_langue` = 1;
UPDATE `contenus` SET `id_contenu` = 5,`titre_html` = 'création de profil',`titre` = 'Création d''un utilisateur',`sous_titre` = 'C''est à ce stade que vous allez définir votre prénom, et surtout votre nom d''utilisateur ainsi que votre mot de pase',`contenu` = '{"titre":"Saisie des informations de connexion",\r\n	"contenu":{"action":"",\r\n				"enctype":"application\\/x-www-form-urlencoded",\r\n				"method":"POST",\r\n				"id":"create_user",\r\n				"evenement_form":"onsubmit=\\"return requestCreateUser(<?php echo AJAX_PATH; ?>,this, printData)\\"",\r\n				"fields":[{"display_name":"Prénom",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"prenom_user",\r\n							"name":"prenom_user"\r\n						},\r\n						{\r\n							"display_name":"Nom",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"nom_user",\r\n							"name":"nom_user"\r\n						},\r\n						{\r\n							"display_name":"Login",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"login_user",\r\n							"name":"login_user"\r\n						},\r\n						{\r\n							"display_name":"Mot de passe",\r\n							"template":"input",\r\n							"type":"password",\r\n							"class":"",\r\n							"id":"pwd_user",\r\n							"name":"pwd_user"\r\n						},	\r\n						{\r\n							"display_name":"re-Saisissez votre Mot de passe",\r\n							"template":"input",\r\n							"type":"password",\r\n							"class":"",\r\n							"id":"pwd_user_2",\r\n							"name":"pwd_user_2"\r\n						},						\r\n						{\r\n							"type":"reset",\r\n							"template":"input",\r\n							"class":"fleft",\r\n							"id":"reset_createUser_form",\r\n							"name":"reset_createUser_form",\r\n							"value":"effacer"\r\n						},\r\n						{\r\n							"type":"submit",\r\n							"template":"input",\r\n							"class":"fleft",\r\n							"id":"submit_createUser_form",\r\n							"name":"submit_createUser_form",\r\n							"value":"Enregistrer"\r\n						}]}}',`position` = 2,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 4,`types_contenus_id_types_contenus` = 3,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 1 WHERE `contenus`.`id_contenu` = 14 AND `contenus`.`langues_id_langue` = 1;
UPDATE `contenus` SET `id_contenu` = 6,`titre_html` = 'ajout_contacts',`titre` = 'Ajout des coordonnées de contact',`sous_titre` = 'Depuis ce sous-formulaire vous pouvez entrer les différentes possibilités de vous joindre',`contenu` = '{"titre":"Saisie des informations de Contact",\r\n	"contenu":{"action":"",\r\n				"enctype":"application\\/x-www-form-urlencoded",\r\n				"method":"POST",\r\n				"id":"create_user",\r\n				"evenement_form":"onsubmit=\\"return requestCreateContact(<?php echo AJAX_PATH; ?>,this, printData)\\"",\r\n				"fields":[{"display_name":"E-mail",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"contact_0",\r\n							"name":"contact_0"\r\n						},						\r\n						{\r\n							"type":"reset",\r\n							"template":"input",\r\n							"class":"fleft",\r\n							"id":"reset_createContact_form",\r\n							"name":"reset_createContact_form",\r\n							"value":"effacer"\r\n						},\r\n						{\r\n							"type":"submit",\r\n							"template":"input",\r\n							"class":"fleft",\r\n							"id":"submit_createContact_form",\r\n							"name":"submit_createContact_form",\r\n							"value":"Enregistrer"\r\n						}]}}',`position` = 3,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 4,`types_contenus_id_types_contenus` = 3,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 1 WHERE `contenus`.`id_contenu` = 15 AND `contenus`.`langues_id_langue` = 1;
UPDATE `contenus` SET `id_contenu` = 7,`titre_html` = 'Creation_adresse',`titre` = 'Création des adresses',`sous_titre` = 'Depuis cette emplacement vous donnerez vos informations de contact postal',`contenu` = '{"titre":"Saisie des informations de base",\r\n	"contenu":{"action":"",\r\n				"enctype":"application\\/x-www-form-urlencoded",\r\n				"method":"POST",\r\n				"id":"create_user",\r\n				"evenement_form":"onsubmit=\\"return requestCreateAdresse(<?php echo AJAX_PATH; ?>,this, printData)\\"",\r\n				"fields":[{"display_name":"Type d''adresse",\r\n							"template":"select",\r\n							"class":"",\r\n							"id":"type_adresse",\r\n							"name":"type_adresse",\r\n							"value":{"1":"Adresse principal",\r\n										"2":"Adresse d''envoi",\r\n										"3":"Adresse de facturation"\r\n									}\r\n						},\r\n						{"display_name":"Adresse",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"adresse_0",\r\n							"name":"adresse_0"\r\n						},\r\n						{"display_name":"Adresse 2",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"adresse_1",\r\n							"name":"adresse_1"\r\n						},\r\n						{"display_name":"NPA",\r\n							"template":"input",\r\n							"type":"text",\r\n							"class":"",\r\n							"id":"adresse_2",\r\n							"name":"adresse_2"\r\n						},\r\n						{"type":"reset",\r\n							"template":"input",\r\n							"class":"fleft",\r\n							"id":"reset_createAdresse_form",\r\n							"name":"reset_createAdresse_form",\r\n							"value":"effacer"\r\n						},\r\n						{"type":"submit",\r\n							"template":"input",\r\n							"class":"fleft",\r\n							"id":"submit_createAdresse_form",\r\n							"name":"submit_createAdresse_form",\r\n							"value":"enregistrer"\r\n						}]}}',`position` = 4,`actif` = '1',`protege` = '0',`websites_id_website` = 2,`categories_id_categorie` = 4,`types_contenus_id_types_contenus` = 3,`utilisateurs_id_utilisateur` = 1,`langues_id_langue` = 1 WHERE `contenus`.`id_contenu` = 16 AND `contenus`.`langues_id_langue` = 1;


UPDATE `pays` SET `id_pays` = 1,`nom_pays` = 'afghanistan',`code_pays` = 'af' WHERE `pays`.`id_pays` = 1;
UPDATE `pays` SET `id_pays` = 2,`nom_pays` = 'afrique-du-sud',`code_pays` = 'za' WHERE `pays`.`id_pays` = 2;
UPDATE `pays` SET `id_pays` = 3,`nom_pays` = 'albanie',`code_pays` = 'al' WHERE `pays`.`id_pays` = 3;
UPDATE `pays` SET `id_pays` = 4,`nom_pays` = 'algerie',`code_pays` = 'dz' WHERE `pays`.`id_pays` = 4;
UPDATE `pays` SET `id_pays` = 5,`nom_pays` = 'allemagne',`code_pays` = 'de' WHERE `pays`.`id_pays` = 5;
UPDATE `pays` SET `id_pays` = 6,`nom_pays` = 'andorre',`code_pays` = 'ad' WHERE `pays`.`id_pays` = 6;
UPDATE `pays` SET `id_pays` = 7,`nom_pays` = 'angola',`code_pays` = 'ao' WHERE `pays`.`id_pays` = 7;
UPDATE `pays` SET `id_pays` = 8,`nom_pays` = 'anguilla',`code_pays` = 'ai' WHERE `pays`.`id_pays` = 8;
UPDATE `pays` SET `id_pays` = 9,`nom_pays` = 'antarctique',`code_pays` = 'aq' WHERE `pays`.`id_pays` = 9;
UPDATE `pays` SET `id_pays` = 10,`nom_pays` = 'antigua-et-barbuda',`code_pays` = 'ag' WHERE `pays`.`id_pays` = 10;
UPDATE `pays` SET `id_pays` = 11,`nom_pays` = 'antilles-neerlandaises',`code_pays` = 'an' WHERE `pays`.`id_pays` = 11;
UPDATE `pays` SET `id_pays` = 12,`nom_pays` = 'arabie-saoudite',`code_pays` = 'sa' WHERE `pays`.`id_pays` = 12;
UPDATE `pays` SET `id_pays` = 13,`nom_pays` = 'argentine',`code_pays` = 'ar' WHERE `pays`.`id_pays` = 13;
UPDATE `pays` SET `id_pays` = 14,`nom_pays` = 'armenie',`code_pays` = 'am' WHERE `pays`.`id_pays` = 14;
UPDATE `pays` SET `id_pays` = 15,`nom_pays` = 'aruba',`code_pays` = 'aw' WHERE `pays`.`id_pays` = 15;
UPDATE `pays` SET `id_pays` = 16,`nom_pays` = 'australie',`code_pays` = 'au' WHERE `pays`.`id_pays` = 16;
UPDATE `pays` SET `id_pays` = 17,`nom_pays` = 'autriche',`code_pays` = 'at' WHERE `pays`.`id_pays` = 17;
UPDATE `pays` SET `id_pays` = 18,`nom_pays` = 'azerbaidjan',`code_pays` = 'az' WHERE `pays`.`id_pays` = 18;
UPDATE `pays` SET `id_pays` = 19,`nom_pays` = 'bahamas',`code_pays` = 'bs' WHERE `pays`.`id_pays` = 19;
UPDATE `pays` SET `id_pays` = 20,`nom_pays` = 'bahrain',`code_pays` = 'bh' WHERE `pays`.`id_pays` = 20;
UPDATE `pays` SET `id_pays` = 21,`nom_pays` = 'bangladesh',`code_pays` = 'bd' WHERE `pays`.`id_pays` = 21;
UPDATE `pays` SET `id_pays` = 22,`nom_pays` = 'belgique',`code_pays` = 'be' WHERE `pays`.`id_pays` = 22;
UPDATE `pays` SET `id_pays` = 23,`nom_pays` = 'belize',`code_pays` = 'bz' WHERE `pays`.`id_pays` = 23;
UPDATE `pays` SET `id_pays` = 24,`nom_pays` = 'benin',`code_pays` = 'bj' WHERE `pays`.`id_pays` = 24;
UPDATE `pays` SET `id_pays` = 25,`nom_pays` = 'bermudes-les',`code_pays` = 'bm' WHERE `pays`.`id_pays` = 25;
UPDATE `pays` SET `id_pays` = 26,`nom_pays` = 'bhoutan',`code_pays` = 'bt' WHERE `pays`.`id_pays` = 26;
UPDATE `pays` SET `id_pays` = 27,`nom_pays` = 'bielorussie',`code_pays` = 'by' WHERE `pays`.`id_pays` = 27;
UPDATE `pays` SET `id_pays` = 28,`nom_pays` = 'bolivie',`code_pays` = 'bo' WHERE `pays`.`id_pays` = 28;
UPDATE `pays` SET `id_pays` = 29,`nom_pays` = 'bosnie-herzegovine',`code_pays` = 'ba' WHERE `pays`.`id_pays` = 29;
UPDATE `pays` SET `id_pays` = 30,`nom_pays` = 'botswana',`code_pays` = 'bw' WHERE `pays`.`id_pays` = 30;
UPDATE `pays` SET `id_pays` = 31,`nom_pays` = 'bouvet-iles',`code_pays` = 'bv' WHERE `pays`.`id_pays` = 31;
UPDATE `pays` SET `id_pays` = 32,`nom_pays` = 'bresil',`code_pays` = 'br' WHERE `pays`.`id_pays` = 32;
UPDATE `pays` SET `id_pays` = 33,`nom_pays` = 'brunei',`code_pays` = 'bn' WHERE `pays`.`id_pays` = 33;
UPDATE `pays` SET `id_pays` = 34,`nom_pays` = 'bulgarie',`code_pays` = 'bg' WHERE `pays`.`id_pays` = 34;
UPDATE `pays` SET `id_pays` = 35,`nom_pays` = 'burkina-faso',`code_pays` = 'bf' WHERE `pays`.`id_pays` = 35;
UPDATE `pays` SET `id_pays` = 36,`nom_pays` = 'burundi',`code_pays` = 'bi' WHERE `pays`.`id_pays` = 36;
UPDATE `pays` SET `id_pays` = 37,`nom_pays` = 'cambodge',`code_pays` = 'kh' WHERE `pays`.`id_pays` = 37;
UPDATE `pays` SET `id_pays` = 38,`nom_pays` = 'cameroun',`code_pays` = 'cm' WHERE `pays`.`id_pays` = 38;
UPDATE `pays` SET `id_pays` = 39,`nom_pays` = 'canada',`code_pays` = 'ca' WHERE `pays`.`id_pays` = 39;
UPDATE `pays` SET `id_pays` = 40,`nom_pays` = 'cap-vert',`code_pays` = 'cv' WHERE `pays`.`id_pays` = 40;
UPDATE `pays` SET `id_pays` = 41,`nom_pays` = 'cayman-iles',`code_pays` = 'ky' WHERE `pays`.`id_pays` = 41;
UPDATE `pays` SET `id_pays` = 42,`nom_pays` = 'chili',`code_pays` = 'cl' WHERE `pays`.`id_pays` = 42;
UPDATE `pays` SET `id_pays` = 43,`nom_pays` = 'chine-rep-pop',`code_pays` = 'cn' WHERE `pays`.`id_pays` = 43;
UPDATE `pays` SET `id_pays` = 44,`nom_pays` = 'christmas-ile',`code_pays` = 'cx' WHERE `pays`.`id_pays` = 44;
UPDATE `pays` SET `id_pays` = 45,`nom_pays` = 'chypre',`code_pays` = 'cy' WHERE `pays`.`id_pays` = 45;
UPDATE `pays` SET `id_pays` = 46,`nom_pays` = 'cocos-iles',`code_pays` = 'cc' WHERE `pays`.`id_pays` = 46;
UPDATE `pays` SET `id_pays` = 47,`nom_pays` = 'colombie',`code_pays` = 'co' WHERE `pays`.`id_pays` = 47;
UPDATE `pays` SET `id_pays` = 48,`nom_pays` = 'comores',`code_pays` = 'km' WHERE `pays`.`id_pays` = 48;
UPDATE `pays` SET `id_pays` = 49,`nom_pays` = 'cook-iles',`code_pays` = 'ck' WHERE `pays`.`id_pays` = 49;
UPDATE `pays` SET `id_pays` = 50,`nom_pays` = 'coree-du-nord',`code_pays` = 'kp' WHERE `pays`.`id_pays` = 50;
UPDATE `pays` SET `id_pays` = 51,`nom_pays` = 'coree-sud',`code_pays` = 'kr' WHERE `pays`.`id_pays` = 51;
UPDATE `pays` SET `id_pays` = 52,`nom_pays` = 'costa-rica',`code_pays` = 'cr' WHERE `pays`.`id_pays` = 52;
UPDATE `pays` SET `id_pays` = 53,`nom_pays` = 'cote-divoire',`code_pays` = 'ci' WHERE `pays`.`id_pays` = 53;
UPDATE `pays` SET `id_pays` = 54,`nom_pays` = 'croatie',`code_pays` = 'hr' WHERE `pays`.`id_pays` = 54;
UPDATE `pays` SET `id_pays` = 55,`nom_pays` = 'cuba',`code_pays` = 'cu' WHERE `pays`.`id_pays` = 55;
UPDATE `pays` SET `id_pays` = 56,`nom_pays` = 'danemark',`code_pays` = 'dk' WHERE `pays`.`id_pays` = 56;
UPDATE `pays` SET `id_pays` = 57,`nom_pays` = 'djibouti',`code_pays` = 'dj' WHERE `pays`.`id_pays` = 57;
UPDATE `pays` SET `id_pays` = 58,`nom_pays` = 'dominique',`code_pays` = 'dm' WHERE `pays`.`id_pays` = 58;
UPDATE `pays` SET `id_pays` = 59,`nom_pays` = 'egypte',`code_pays` = 'eg' WHERE `pays`.`id_pays` = 59;
UPDATE `pays` SET `id_pays` = 60,`nom_pays` = 'el-salvador',`code_pays` = 'sv' WHERE `pays`.`id_pays` = 60;
UPDATE `pays` SET `id_pays` = 61,`nom_pays` = 'emirats-arabes-unis',`code_pays` = 'ae' WHERE `pays`.`id_pays` = 61;
UPDATE `pays` SET `id_pays` = 62,`nom_pays` = 'equateur',`code_pays` = 'ec' WHERE `pays`.`id_pays` = 62;
UPDATE `pays` SET `id_pays` = 63,`nom_pays` = 'erythree',`code_pays` = 'er' WHERE `pays`.`id_pays` = 63;
UPDATE `pays` SET `id_pays` = 64,`nom_pays` = 'espagne',`code_pays` = 'es' WHERE `pays`.`id_pays` = 64;
UPDATE `pays` SET `id_pays` = 65,`nom_pays` = 'estonie',`code_pays` = 'ee' WHERE `pays`.`id_pays` = 65;
UPDATE `pays` SET `id_pays` = 66,`nom_pays` = 'etats-unis',`code_pays` = 'us' WHERE `pays`.`id_pays` = 66;
UPDATE `pays` SET `id_pays` = 67,`nom_pays` = 'ethiopie',`code_pays` = 'et' WHERE `pays`.`id_pays` = 67;
UPDATE `pays` SET `id_pays` = 68,`nom_pays` = 'falkland-ile',`code_pays` = 'fk' WHERE `pays`.`id_pays` = 68;
UPDATE `pays` SET `id_pays` = 69,`nom_pays` = 'feroe-iles',`code_pays` = 'fo' WHERE `pays`.`id_pays` = 69;
UPDATE `pays` SET `id_pays` = 70,`nom_pays` = 'fidji-republique-des',`code_pays` = 'fj' WHERE `pays`.`id_pays` = 70;
UPDATE `pays` SET `id_pays` = 71,`nom_pays` = 'finlande',`code_pays` = 'fi' WHERE `pays`.`id_pays` = 71;
UPDATE `pays` SET `id_pays` = 72,`nom_pays` = 'france',`code_pays` = 'fr' WHERE `pays`.`id_pays` = 72;
UPDATE `pays` SET `id_pays` = 73,`nom_pays` = 'gabon',`code_pays` = 'ga' WHERE `pays`.`id_pays` = 73;
UPDATE `pays` SET `id_pays` = 74,`nom_pays` = 'gambie',`code_pays` = 'gm' WHERE `pays`.`id_pays` = 74;
UPDATE `pays` SET `id_pays` = 75,`nom_pays` = 'georgie',`code_pays` = 'ge' WHERE `pays`.`id_pays` = 75;
UPDATE `pays` SET `id_pays` = 76,`nom_pays` = 'georgie-du-sud-et-sandwich-du-sud-iles',`code_pays` = 'gs' WHERE `pays`.`id_pays` = 76;
UPDATE `pays` SET `id_pays` = 77,`nom_pays` = 'ghana',`code_pays` = 'gh' WHERE `pays`.`id_pays` = 77;
UPDATE `pays` SET `id_pays` = 78,`nom_pays` = 'gibraltar',`code_pays` = 'gi' WHERE `pays`.`id_pays` = 78;
UPDATE `pays` SET `id_pays` = 79,`nom_pays` = 'grece',`code_pays` = 'gr' WHERE `pays`.`id_pays` = 79;
UPDATE `pays` SET `id_pays` = 80,`nom_pays` = 'grenade',`code_pays` = 'gd' WHERE `pays`.`id_pays` = 80;
UPDATE `pays` SET `id_pays` = 81,`nom_pays` = 'groenland',`code_pays` = 'gl' WHERE `pays`.`id_pays` = 81;
UPDATE `pays` SET `id_pays` = 82,`nom_pays` = 'guadeloupe',`code_pays` = 'gp' WHERE `pays`.`id_pays` = 82;
UPDATE `pays` SET `id_pays` = 83,`nom_pays` = 'guam',`code_pays` = 'gu' WHERE `pays`.`id_pays` = 83;
UPDATE `pays` SET `id_pays` = 84,`nom_pays` = 'guatemala',`code_pays` = 'gt' WHERE `pays`.`id_pays` = 84;
UPDATE `pays` SET `id_pays` = 85,`nom_pays` = 'guinee',`code_pays` = 'gn' WHERE `pays`.`id_pays` = 85;
UPDATE `pays` SET `id_pays` = 86,`nom_pays` = 'guinee-bissau',`code_pays` = 'gw' WHERE `pays`.`id_pays` = 86;
UPDATE `pays` SET `id_pays` = 87,`nom_pays` = 'guinee-equatoriale',`code_pays` = 'gq' WHERE `pays`.`id_pays` = 87;
UPDATE `pays` SET `id_pays` = 88,`nom_pays` = 'guyane',`code_pays` = 'gy' WHERE `pays`.`id_pays` = 88;
UPDATE `pays` SET `id_pays` = 89,`nom_pays` = 'guyane-francaise',`code_pays` = 'gf' WHERE `pays`.`id_pays` = 89;
UPDATE `pays` SET `id_pays` = 90,`nom_pays` = 'haiti',`code_pays` = 'ht' WHERE `pays`.`id_pays` = 90;
UPDATE `pays` SET `id_pays` = 91,`nom_pays` = 'heard-et-mcdonald-iles',`code_pays` = 'hm' WHERE `pays`.`id_pays` = 91;
UPDATE `pays` SET `id_pays` = 92,`nom_pays` = 'honduras',`code_pays` = 'hn' WHERE `pays`.`id_pays` = 92;
UPDATE `pays` SET `id_pays` = 93,`nom_pays` = 'hong-kong',`code_pays` = 'hk' WHERE `pays`.`id_pays` = 93;
UPDATE `pays` SET `id_pays` = 94,`nom_pays` = 'hongrie',`code_pays` = 'hu' WHERE `pays`.`id_pays` = 94;
UPDATE `pays` SET `id_pays` = 95,`nom_pays` = 'iles-mineures-eloignees-des-etats-unis',`code_pays` = 'um' WHERE `pays`.`id_pays` = 95;
UPDATE `pays` SET `id_pays` = 96,`nom_pays` = 'inde',`code_pays` = 'in' WHERE `pays`.`id_pays` = 96;
UPDATE `pays` SET `id_pays` = 97,`nom_pays` = 'indonesie',`code_pays` = 'id' WHERE `pays`.`id_pays` = 97;
UPDATE `pays` SET `id_pays` = 98,`nom_pays` = 'irak',`code_pays` = 'iq' WHERE `pays`.`id_pays` = 98;
UPDATE `pays` SET `id_pays` = 99,`nom_pays` = 'iran',`code_pays` = 'ir' WHERE `pays`.`id_pays` = 99;
UPDATE `pays` SET `id_pays` = 100,`nom_pays` = 'irlande',`code_pays` = 'ie' WHERE `pays`.`id_pays` = 100;
UPDATE `pays` SET `id_pays` = 101,`nom_pays` = 'islande',`code_pays` = 'is' WHERE `pays`.`id_pays` = 101;
UPDATE `pays` SET `id_pays` = 102,`nom_pays` = 'israel',`code_pays` = 'il' WHERE `pays`.`id_pays` = 102;
UPDATE `pays` SET `id_pays` = 103,`nom_pays` = 'italie',`code_pays` = 'it' WHERE `pays`.`id_pays` = 103;
UPDATE `pays` SET `id_pays` = 104,`nom_pays` = 'jamaique',`code_pays` = 'jm' WHERE `pays`.`id_pays` = 104;
UPDATE `pays` SET `id_pays` = 105,`nom_pays` = 'japon',`code_pays` = 'jp' WHERE `pays`.`id_pays` = 105;
UPDATE `pays` SET `id_pays` = 106,`nom_pays` = 'jordanie',`code_pays` = 'jo' WHERE `pays`.`id_pays` = 106;
UPDATE `pays` SET `id_pays` = 107,`nom_pays` = 'kazakhstan',`code_pays` = 'kz' WHERE `pays`.`id_pays` = 107;
UPDATE `pays` SET `id_pays` = 108,`nom_pays` = 'kenya',`code_pays` = 'ke' WHERE `pays`.`id_pays` = 108;
UPDATE `pays` SET `id_pays` = 109,`nom_pays` = 'kirghizistan',`code_pays` = 'kg' WHERE `pays`.`id_pays` = 109;
UPDATE `pays` SET `id_pays` = 110,`nom_pays` = 'kiribati',`code_pays` = 'ki' WHERE `pays`.`id_pays` = 110;
UPDATE `pays` SET `id_pays` = 111,`nom_pays` = 'koweit',`code_pays` = 'kw' WHERE `pays`.`id_pays` = 111;
UPDATE `pays` SET `id_pays` = 112,`nom_pays` = 'la-barbad',`code_pays` = 'bb' WHERE `pays`.`id_pays` = 112;
UPDATE `pays` SET `id_pays` = 113,`nom_pays` = 'laos',`code_pays` = 'la' WHERE `pays`.`id_pays` = 113;
UPDATE `pays` SET `id_pays` = 114,`nom_pays` = 'lesotho',`code_pays` = 'ls' WHERE `pays`.`id_pays` = 114;
UPDATE `pays` SET `id_pays` = 115,`nom_pays` = 'lettonie',`code_pays` = 'lv' WHERE `pays`.`id_pays` = 115;
UPDATE `pays` SET `id_pays` = 116,`nom_pays` = 'liban',`code_pays` = 'lb' WHERE `pays`.`id_pays` = 116;
UPDATE `pays` SET `id_pays` = 117,`nom_pays` = 'liberia',`code_pays` = 'lr' WHERE `pays`.`id_pays` = 117;
UPDATE `pays` SET `id_pays` = 118,`nom_pays` = 'libye',`code_pays` = 'ly' WHERE `pays`.`id_pays` = 118;
UPDATE `pays` SET `id_pays` = 119,`nom_pays` = 'liechtenstein',`code_pays` = 'li' WHERE `pays`.`id_pays` = 119;
UPDATE `pays` SET `id_pays` = 120,`nom_pays` = 'lithuanie',`code_pays` = 'lt' WHERE `pays`.`id_pays` = 120;
UPDATE `pays` SET `id_pays` = 121,`nom_pays` = 'luxembourg',`code_pays` = 'lu' WHERE `pays`.`id_pays` = 121;
UPDATE `pays` SET `id_pays` = 122,`nom_pays` = 'macau',`code_pays` = 'mo' WHERE `pays`.`id_pays` = 122;
UPDATE `pays` SET `id_pays` = 123,`nom_pays` = 'macedoine',`code_pays` = 'mk' WHERE `pays`.`id_pays` = 123;
UPDATE `pays` SET `id_pays` = 124,`nom_pays` = 'madagascar',`code_pays` = 'mg' WHERE `pays`.`id_pays` = 124;
UPDATE `pays` SET `id_pays` = 125,`nom_pays` = 'malaisie',`code_pays` = 'my' WHERE `pays`.`id_pays` = 125;
UPDATE `pays` SET `id_pays` = 126,`nom_pays` = 'malawi',`code_pays` = 'mw' WHERE `pays`.`id_pays` = 126;
UPDATE `pays` SET `id_pays` = 127,`nom_pays` = 'maldives-iles',`code_pays` = 'mv' WHERE `pays`.`id_pays` = 127;
UPDATE `pays` SET `id_pays` = 128,`nom_pays` = 'mali',`code_pays` = 'ml' WHERE `pays`.`id_pays` = 128;
UPDATE `pays` SET `id_pays` = 129,`nom_pays` = 'malte',`code_pays` = 'mt' WHERE `pays`.`id_pays` = 129;
UPDATE `pays` SET `id_pays` = 130,`nom_pays` = 'mariannes-du-nord-iles',`code_pays` = 'mp' WHERE `pays`.`id_pays` = 130;
UPDATE `pays` SET `id_pays` = 131,`nom_pays` = 'maroc',`code_pays` = 'ma' WHERE `pays`.`id_pays` = 131;
UPDATE `pays` SET `id_pays` = 132,`nom_pays` = 'marshall-iles',`code_pays` = 'mh' WHERE `pays`.`id_pays` = 132;
UPDATE `pays` SET `id_pays` = 133,`nom_pays` = 'martinique',`code_pays` = 'mq' WHERE `pays`.`id_pays` = 133;
UPDATE `pays` SET `id_pays` = 134,`nom_pays` = 'maurice',`code_pays` = 'mu' WHERE `pays`.`id_pays` = 134;
UPDATE `pays` SET `id_pays` = 135,`nom_pays` = 'mauritanie',`code_pays` = 'mr' WHERE `pays`.`id_pays` = 135;
UPDATE `pays` SET `id_pays` = 136,`nom_pays` = 'mayotte',`code_pays` = 'yt' WHERE `pays`.`id_pays` = 136;
UPDATE `pays` SET `id_pays` = 137,`nom_pays` = 'mexique',`code_pays` = 'mx' WHERE `pays`.`id_pays` = 137;
UPDATE `pays` SET `id_pays` = 138,`nom_pays` = 'micronesie-etats-federes-de',`code_pays` = 'fm' WHERE `pays`.`id_pays` = 138;
UPDATE `pays` SET `id_pays` = 139,`nom_pays` = 'moldavie',`code_pays` = 'md' WHERE `pays`.`id_pays` = 139;
UPDATE `pays` SET `id_pays` = 140,`nom_pays` = 'monaco',`code_pays` = 'mc' WHERE `pays`.`id_pays` = 140;
UPDATE `pays` SET `id_pays` = 141,`nom_pays` = 'mongolie',`code_pays` = 'mn' WHERE `pays`.`id_pays` = 141;
UPDATE `pays` SET `id_pays` = 142,`nom_pays` = 'montserrat',`code_pays` = 'ms' WHERE `pays`.`id_pays` = 142;
UPDATE `pays` SET `id_pays` = 143,`nom_pays` = 'mozambique',`code_pays` = 'mz' WHERE `pays`.`id_pays` = 143;
UPDATE `pays` SET `id_pays` = 144,`nom_pays` = 'myanmar',`code_pays` = 'mm' WHERE `pays`.`id_pays` = 144;
UPDATE `pays` SET `id_pays` = 145,`nom_pays` = 'namibie',`code_pays` = 'na' WHERE `pays`.`id_pays` = 145;
UPDATE `pays` SET `id_pays` = 146,`nom_pays` = 'nauru',`code_pays` = 'nr' WHERE `pays`.`id_pays` = 146;
UPDATE `pays` SET `id_pays` = 147,`nom_pays` = 'nepal',`code_pays` = 'np' WHERE `pays`.`id_pays` = 147;
UPDATE `pays` SET `id_pays` = 148,`nom_pays` = 'nicaragua',`code_pays` = 'ni' WHERE `pays`.`id_pays` = 148;
UPDATE `pays` SET `id_pays` = 149,`nom_pays` = 'niger',`code_pays` = 'ne' WHERE `pays`.`id_pays` = 149;
UPDATE `pays` SET `id_pays` = 150,`nom_pays` = 'nigeria',`code_pays` = 'ng' WHERE `pays`.`id_pays` = 150;
UPDATE `pays` SET `id_pays` = 151,`nom_pays` = 'niue',`code_pays` = 'nu' WHERE `pays`.`id_pays` = 151;
UPDATE `pays` SET `id_pays` = 152,`nom_pays` = 'norfolk-iles',`code_pays` = 'nf' WHERE `pays`.`id_pays` = 152;
UPDATE `pays` SET `id_pays` = 153,`nom_pays` = 'norvege',`code_pays` = 'no' WHERE `pays`.`id_pays` = 153;
UPDATE `pays` SET `id_pays` = 154,`nom_pays` = 'nouvelle-caledonie',`code_pays` = 'nc' WHERE `pays`.`id_pays` = 154;
UPDATE `pays` SET `id_pays` = 155,`nom_pays` = 'nouvelle-zelande',`code_pays` = 'nz' WHERE `pays`.`id_pays` = 155;
UPDATE `pays` SET `id_pays` = 156,`nom_pays` = 'oman',`code_pays` = 'om' WHERE `pays`.`id_pays` = 156;
UPDATE `pays` SET `id_pays` = 157,`nom_pays` = 'ouganda',`code_pays` = 'ug' WHERE `pays`.`id_pays` = 157;
UPDATE `pays` SET `id_pays` = 158,`nom_pays` = 'ouzbekistan',`code_pays` = 'uz' WHERE `pays`.`id_pays` = 158;
UPDATE `pays` SET `id_pays` = 159,`nom_pays` = 'pakistan',`code_pays` = 'pk' WHERE `pays`.`id_pays` = 159;
UPDATE `pays` SET `id_pays` = 160,`nom_pays` = 'palau',`code_pays` = 'pw' WHERE `pays`.`id_pays` = 160;
UPDATE `pays` SET `id_pays` = 161,`nom_pays` = 'panama',`code_pays` = 'pa' WHERE `pays`.`id_pays` = 161;
UPDATE `pays` SET `id_pays` = 162,`nom_pays` = 'papouasie-nouvelle-guinee',`code_pays` = 'pg' WHERE `pays`.`id_pays` = 162;
UPDATE `pays` SET `id_pays` = 163,`nom_pays` = 'paraguay',`code_pays` = 'py' WHERE `pays`.`id_pays` = 163;
UPDATE `pays` SET `id_pays` = 164,`nom_pays` = 'pays-bas',`code_pays` = 'nl' WHERE `pays`.`id_pays` = 164;
UPDATE `pays` SET `id_pays` = 165,`nom_pays` = 'perou',`code_pays` = 'pe' WHERE `pays`.`id_pays` = 165;
UPDATE `pays` SET `id_pays` = 166,`nom_pays` = 'philippines',`code_pays` = 'ph' WHERE `pays`.`id_pays` = 166;
UPDATE `pays` SET `id_pays` = 167,`nom_pays` = 'pitcairn-iles',`code_pays` = 'pn' WHERE `pays`.`id_pays` = 167;
UPDATE `pays` SET `id_pays` = 168,`nom_pays` = 'pologne',`code_pays` = 'pl' WHERE `pays`.`id_pays` = 168;
UPDATE `pays` SET `id_pays` = 169,`nom_pays` = 'polynesie-francaise',`code_pays` = 'pf' WHERE `pays`.`id_pays` = 169;
UPDATE `pays` SET `id_pays` = 170,`nom_pays` = 'porto-rico',`code_pays` = 'pr' WHERE `pays`.`id_pays` = 170;
UPDATE `pays` SET `id_pays` = 171,`nom_pays` = 'portugal',`code_pays` = 'pt' WHERE `pays`.`id_pays` = 171;
UPDATE `pays` SET `id_pays` = 172,`nom_pays` = 'qatar',`code_pays` = 'qa' WHERE `pays`.`id_pays` = 172;
UPDATE `pays` SET `id_pays` = 173,`nom_pays` = 'rep-dem-du-congo',`code_pays` = 'cg' WHERE `pays`.`id_pays` = 173;
UPDATE `pays` SET `id_pays` = 174,`nom_pays` = 'republique-centrafricaine',`code_pays` = 'cf' WHERE `pays`.`id_pays` = 174;
UPDATE `pays` SET `id_pays` = 175,`nom_pays` = 'republique-dominicaine',`code_pays` = 'do' WHERE `pays`.`id_pays` = 175;
UPDATE `pays` SET `id_pays` = 176,`nom_pays` = 'republique-tcheque',`code_pays` = 'cz' WHERE `pays`.`id_pays` = 176;
UPDATE `pays` SET `id_pays` = 177,`nom_pays` = 'reunion-la',`code_pays` = 're' WHERE `pays`.`id_pays` = 177;
UPDATE `pays` SET `id_pays` = 178,`nom_pays` = 'roumanie',`code_pays` = 'ro' WHERE `pays`.`id_pays` = 178;
UPDATE `pays` SET `id_pays` = 179,`nom_pays` = 'royaume-uni',`code_pays` = 'uk' WHERE `pays`.`id_pays` = 179;
UPDATE `pays` SET `id_pays` = 180,`nom_pays` = 'russie',`code_pays` = 'ru' WHERE `pays`.`id_pays` = 180;
UPDATE `pays` SET `id_pays` = 181,`nom_pays` = 'rwanda',`code_pays` = 'rw' WHERE `pays`.`id_pays` = 181;
UPDATE `pays` SET `id_pays` = 182,`nom_pays` = 'sahara-occidental',`code_pays` = 'eh' WHERE `pays`.`id_pays` = 182;
UPDATE `pays` SET `id_pays` = 183,`nom_pays` = 'sainte-helene',`code_pays` = 'sh' WHERE `pays`.`id_pays` = 183;
UPDATE `pays` SET `id_pays` = 184,`nom_pays` = 'sainte-lucie',`code_pays` = 'lc' WHERE `pays`.`id_pays` = 184;
UPDATE `pays` SET `id_pays` = 185,`nom_pays` = 'saint-kitts-et-nevis',`code_pays` = 'kn' WHERE `pays`.`id_pays` = 185;
UPDATE `pays` SET `id_pays` = 186,`nom_pays` = 'saint-marin-rep-de',`code_pays` = 'sm' WHERE `pays`.`id_pays` = 186;
UPDATE `pays` SET `id_pays` = 187,`nom_pays` = 'saint-pierre-et-miquelon',`code_pays` = 'pm' WHERE `pays`.`id_pays` = 187;
UPDATE `pays` SET `id_pays` = 188,`nom_pays` = 'saint-vincent-et-les-grenadines',`code_pays` = 'vc' WHERE `pays`.`id_pays` = 188;
UPDATE `pays` SET `id_pays` = 189,`nom_pays` = 'samoa',`code_pays` = 'as' WHERE `pays`.`id_pays` = 189;
UPDATE `pays` SET `id_pays` = 190,`nom_pays` = 'samoa',`code_pays` = 'ws' WHERE `pays`.`id_pays` = 190;
UPDATE `pays` SET `id_pays` = 191,`nom_pays` = 'sao-tome-et-principe-rep',`code_pays` = 'st' WHERE `pays`.`id_pays` = 191;
UPDATE `pays` SET `id_pays` = 192,`nom_pays` = 'senegal',`code_pays` = 'sn' WHERE `pays`.`id_pays` = 192;
UPDATE `pays` SET `id_pays` = 193,`nom_pays` = 'seychelles',`code_pays` = 'sc' WHERE `pays`.`id_pays` = 193;
UPDATE `pays` SET `id_pays` = 194,`nom_pays` = 'sierra-leone',`code_pays` = 'sl' WHERE `pays`.`id_pays` = 194;
UPDATE `pays` SET `id_pays` = 195,`nom_pays` = 'singapour',`code_pays` = 'sg' WHERE `pays`.`id_pays` = 195;
UPDATE `pays` SET `id_pays` = 196,`nom_pays` = 'slovaquie',`code_pays` = 'sk' WHERE `pays`.`id_pays` = 196;
UPDATE `pays` SET `id_pays` = 197,`nom_pays` = 'slovenie',`code_pays` = 'si' WHERE `pays`.`id_pays` = 197;
UPDATE `pays` SET `id_pays` = 198,`nom_pays` = 'somalie',`code_pays` = 'so' WHERE `pays`.`id_pays` = 198;
UPDATE `pays` SET `id_pays` = 199,`nom_pays` = 'soudan',`code_pays` = 'sd' WHERE `pays`.`id_pays` = 199;
UPDATE `pays` SET `id_pays` = 200,`nom_pays` = 'sri-lanka',`code_pays` = 'lk' WHERE `pays`.`id_pays` = 200;
UPDATE `pays` SET `id_pays` = 201,`nom_pays` = 'suede',`code_pays` = 'se' WHERE `pays`.`id_pays` = 201;
UPDATE `pays` SET `id_pays` = 202,`nom_pays` = 'suisse',`code_pays` = 'ch' WHERE `pays`.`id_pays` = 202;
UPDATE `pays` SET `id_pays` = 203,`nom_pays` = 'suriname',`code_pays` = 'sr' WHERE `pays`.`id_pays` = 203;
UPDATE `pays` SET `id_pays` = 204,`nom_pays` = 'svalbard-et-jan-mayen-iles',`code_pays` = 'sj' WHERE `pays`.`id_pays` = 204;
UPDATE `pays` SET `id_pays` = 205,`nom_pays` = 'swaziland',`code_pays` = 'sz' WHERE `pays`.`id_pays` = 205;
UPDATE `pays` SET `id_pays` = 206,`nom_pays` = 'syrie',`code_pays` = 'sy' WHERE `pays`.`id_pays` = 206;
UPDATE `pays` SET `id_pays` = 207,`nom_pays` = 'tadjikistan',`code_pays` = 'tj' WHERE `pays`.`id_pays` = 207;
UPDATE `pays` SET `id_pays` = 208,`nom_pays` = 'taiwan',`code_pays` = 'tw' WHERE `pays`.`id_pays` = 208;
UPDATE `pays` SET `id_pays` = 209,`nom_pays` = 'tanzanie',`code_pays` = 'tz' WHERE `pays`.`id_pays` = 209;
UPDATE `pays` SET `id_pays` = 210,`nom_pays` = 'tchad',`code_pays` = 'td' WHERE `pays`.`id_pays` = 210;
UPDATE `pays` SET `id_pays` = 211,`nom_pays` = 'territoire-britannique-de-locean-indien',`code_pays` = 'io' WHERE `pays`.`id_pays` = 211;
UPDATE `pays` SET `id_pays` = 212,`nom_pays` = 'territoires-francais-du-sud',`code_pays` = 'tf' WHERE `pays`.`id_pays` = 212;
UPDATE `pays` SET `id_pays` = 213,`nom_pays` = 'thailande',`code_pays` = 'th' WHERE `pays`.`id_pays` = 213;
UPDATE `pays` SET `id_pays` = 214,`nom_pays` = 'timor',`code_pays` = 'tp' WHERE `pays`.`id_pays` = 214;
UPDATE `pays` SET `id_pays` = 215,`nom_pays` = 'togo',`code_pays` = 'tg' WHERE `pays`.`id_pays` = 215;
UPDATE `pays` SET `id_pays` = 216,`nom_pays` = 'tokelau',`code_pays` = 'tk' WHERE `pays`.`id_pays` = 216;
UPDATE `pays` SET `id_pays` = 217,`nom_pays` = 'tonga',`code_pays` = 'to' WHERE `pays`.`id_pays` = 217;
UPDATE `pays` SET `id_pays` = 218,`nom_pays` = 'trinite-et-tobago',`code_pays` = 'tt' WHERE `pays`.`id_pays` = 218;
UPDATE `pays` SET `id_pays` = 219,`nom_pays` = 'tunisie',`code_pays` = 'tn' WHERE `pays`.`id_pays` = 219;
UPDATE `pays` SET `id_pays` = 220,`nom_pays` = 'turkmenistan',`code_pays` = 'tm' WHERE `pays`.`id_pays` = 220;
UPDATE `pays` SET `id_pays` = 221,`nom_pays` = 'turks-et-caiques-iles',`code_pays` = 'tc' WHERE `pays`.`id_pays` = 221;
UPDATE `pays` SET `id_pays` = 222,`nom_pays` = 'turquie',`code_pays` = 'tr' WHERE `pays`.`id_pays` = 222;
UPDATE `pays` SET `id_pays` = 223,`nom_pays` = 'tuvalu',`code_pays` = 'tv' WHERE `pays`.`id_pays` = 223;
UPDATE `pays` SET `id_pays` = 224,`nom_pays` = 'ukraine',`code_pays` = 'ua' WHERE `pays`.`id_pays` = 224;
UPDATE `pays` SET `id_pays` = 225,`nom_pays` = 'uruguay',`code_pays` = 'uy' WHERE `pays`.`id_pays` = 225;
UPDATE `pays` SET `id_pays` = 226,`nom_pays` = 'vanuatu',`code_pays` = 'vu' WHERE `pays`.`id_pays` = 226;
UPDATE `pays` SET `id_pays` = 227,`nom_pays` = 'vatican-etat-du',`code_pays` = 'va' WHERE `pays`.`id_pays` = 227;
UPDATE `pays` SET `id_pays` = 228,`nom_pays` = 'venezuela',`code_pays` = 've' WHERE `pays`.`id_pays` = 228;
UPDATE `pays` SET `id_pays` = 229,`nom_pays` = 'vierges-britanniques-iles',`code_pays` = 'vg' WHERE `pays`.`id_pays` = 229;
UPDATE `pays` SET `id_pays` = 230,`nom_pays` = 'vierges-iles',`code_pays` = 'vi' WHERE `pays`.`id_pays` = 230;
UPDATE `pays` SET `id_pays` = 231,`nom_pays` = 'vietnam',`code_pays` = 'vn' WHERE `pays`.`id_pays` = 231;
UPDATE `pays` SET `id_pays` = 232,`nom_pays` = 'wallis-et-futuna-iles',`code_pays` = 'wf' WHERE `pays`.`id_pays` = 232;
UPDATE `pays` SET `id_pays` = 233,`nom_pays` = 'yemen',`code_pays` = 'ye' WHERE `pays`.`id_pays` = 233;
UPDATE `pays` SET `id_pays` = 234,`nom_pays` = 'yougoslavie',`code_pays` = 'yu' WHERE `pays`.`id_pays` = 234;
UPDATE `pays` SET `id_pays` = 235,`nom_pays` = 'zaire',`code_pays` = 'zr' WHERE `pays`.`id_pays` = 235;
UPDATE `pays` SET `id_pays` = 236,`nom_pays` = 'zambie',`code_pays` = 'zm' WHERE `pays`.`id_pays` = 236;
UPDATE `pays` SET `id_pays` = 237,`nom_pays` = 'zimbabwe',`code_pays` = 'zw' WHERE `pays`.`id_pays` = 237;